In [1]:
!which pip

/home/virk/devs/WorkProjects/DTIP/venv/bin/pip


In [25]:
from fsl.data import dicom

from dtip.utils import load_config, ROOT_DIR


# Returns True if dcm2niix is present, and recent enough, False otherwise.
dicom.enabled()

True

In [26]:
CNF = load_config(ROOT_DIR/'config/default.yaml')

In [11]:
import nibabel as nib
from pathlib import Path

In [5]:
input_path = Path('/media/virk/MyEHDD/ITS/1_nifti/1_1')
output_path = Path('/media/virk/MyEHDD/ITS/2_dti')

In [6]:
!ls {input_path}

ANGIOs903a1009A.nii.gz        Sag3DFLAIRs601a1006.txt
ANGIOs903a1009A.txt           Sag3DT1s1101a1011.nii.gz
ANGIOs903a1009B.nii.gz        Sag3DT1s1101a1011.txt
ANGIOs903a1009B.txt           Surveys101a1001A.nii.gz
ANGIOs903a1009C.nii.gz        Surveys101a1001A.txt
ANGIOs903a1009C.txt           Surveys101a1001B.nii.gz
ANGIOs903a1009D.nii.gz        Surveys101a1001B.txt
ANGIOs903a1009D.txt           Surveys101a1001.nii.gz
ANGIOs903a1009E.nii.gz        Surveys101a1001.txt
ANGIOs903a1009E.txt           T1W3DTFEs201a1002.nii.gz
ANGIOs903a1009F.nii.gz        T1W3DTFEs201a1002.txt
ANGIOs903a1009F.txt           T23Ds301a1003.nii.gz
ANGIOs903a1009G.nii.gz        T23Ds301a1003.txt
ANGIOs903a1009G.txt           TRAs1102a1011.nii.gz
ANGIOs903a1009H.nii.gz        TRAs1102a1011.txt
ANGIOs903a1009H.txt           TRAs1103a1011.nii.gz
ANGIOs903a1009I.nii.gz        TRAs1103a1011.txt
ANGIOs903a1009I.txt           TRAs1104a1011.nii.gz
ANGIOs903a1009.nii.gz         TRAs1104a1011.txt
ANGIOs903a1009.txt     

In [25]:
imgpath = Path('/media/virk/MyEHDD/ITS/1_nifti/1_1/xDTImediumisos501a1005.nii.gz')
imgpath

PosixPath('/media/virk/MyEHDD/ITS/1_nifti/1_1/xDTImediumisos501a1005.nii.gz')

In [27]:
img = nib.load(imgpath)

In [32]:
img.header.

In [52]:
from dtip.convert import method_dcm2niix

In [53]:
src = '/media/virk/MyEHDD/PGI_ITS_RAW/RAW/1_1'
dst = 'test2'

In [58]:
method_dcm2niix(src, dst)

dcm2niix conversion... [ =    ]Chris Rorden's dcm2niiX version v1.0.20181125  (JP2:OpenJPEG) GCC9.3.0 (64-bit Linux)
Found 4090 DICOM file(s)
Skipping Spectroscopy DICOM '/media/virk/MyEHDD/PGI_ITS_RAW/RAW/1_1/S13010/I10'
Convert 1 DICOM as test2/s2D_PRESS_144_s1301 (20x24x1x2)
compress: "/usr/bin/pigz" -n -f -6 "test2/s2D_PRESS_144_s1301.nii"
Using RWVSlope:RWVIntercept = 39.2523:0
 Philips Scaling Values RS:RI:SS = 39.2523:0:0.184911 (see PMC3998685)
Convert 160 DICOM as test2/VENO_TOF_s1001 (400x400x160x1)
dcm2niix conversion... [=     ]compress: "/usr/bin/pigz" -n -f -6 "test2/VENO_TOF_s1001.nii"
slices not stacked: orientation varies (vNav or localizer?) [0.999869 -0.00206645 0.0160497 0.0161571 0.072305 -0.997252] != [0.999869 -0.00206645 0.0160497 0.000900296 0.99738 0.0723289]
Using RWVSlope:RWVIntercept = 5.22173:0
 Philips Scaling Values RS:RI:SS = 5.22173:0:0.184911 (see PMC3998685)
Convert 1 DICOM as test2/MIP_-_VENO_TOF_s1002_i00001 (400x400x1x1)
compress: "/usr/bin/pigz" 

dcm2niix conversion... [   =  ]compress: "/usr/bin/pigz" -n -f -6 "test2/Survey_s101_i00007.nii"
Dims 320 320 124 1 1
 Distance from first slice:
dx=[0 1.00001 2 3.00001 4.00001 5.00001 6.00001 7.00002 8.00001 9.00002 10 11 12 13 14 15 16 17 18 19 20 21 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41.0001 42.0001 43.0001 44.0001 45.0001 46.0001 47.0001 48.0001 49.0001 50.0001 51.0001 52.0001 53.0001 54.0001 55.0001 56.0001 57.0001 58.0001 59.0001 60.0001 61.0001 62.0001 63.0001 64.0001 65.0001 66.0001 67.0001 68.0001 69.0001 70.0001 71.0001 72.0001 73.0001 74.0001 75.0001 76.0001 78.0001 79.0001 80.0001 83.0001 86.0001 87.0001 88.0001 90.0001 91.0001 92.0001 93.0001 96.0001 97.0001 98.0001 102 106 109 111 114 117 118 119 121 122 123 125 127 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
instance=[ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 

dcm2niix conversion... [    = ] 2283 2284 2285 2286 2287 2288 2289 2290 2291 2292 2293 2294 2295 2296 2297 2298 2299 2300 2301 2302 2303 2304 2305 2306 2307 2308 2309 2310 2343 2344 2345 2346 2347 2348 2349 2350 2351 2352 2353 2354 2355 2356 2357 2358 2359 2360 2361 2362 2363 2364 2365 2366 2367 2368 2369 2370 2371 2372 2373 2374 2375 2376 2409 2410 2411 2412 2413 2414 2415 2416 2417 2418 2419 2420 2421 2422 2423 2424 2425 2426 2427 2428 2429 2430 2431 2432 2433 2434 2435 2436 2437 2438 2439 2440 2441 2442 2475 2476 2477 2478 2479 2480 2481 2482 2483 2484 2485 2486 2487 2488 2489 2490 2491 2492 2493 2494 2495 2496 2497 2498 2499 2500 2501 2502 2503 2504 2505 2506 2507 2508 2541 2542 2543 2544 2545 2546 2547 2548 2549 2550 2551 2552 2553 2554 2555 2556 2557 2558 2559 2560 2561 2562 2563 2564 2565 2566 2567 2568 2569 2570 2571 2572 2573 2574 2607 2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632 2633 2634 2635 263

dcm2niix conversion... [   =  ]compress: "/usr/bin/pigz" -n -f -6 "test2/Sag_3D_FLAIR_s601.nii"
 Cropping from slice 0 to 299 (of 384)
compress: "/usr/bin/pigz" -n -f -6 "test2/Sag_3D_FLAIR_s601_Crop_1.nii"
Using RWVSlope:RWVIntercept = 5.19072:0
 Philips Scaling Values RS:RI:SS = 5.19072:0:0.00953466 (see PMC3998685)
Convert 9 DICOM as test2/TRA_s602_real (1024x1024x9x1)
dcm2niix conversion... [     =]compress: "/usr/bin/pigz" -n -f -6 "test2/TRA_s602_real.nii"
Using RWVSlope:RWVIntercept = 5.19072:0
 Philips Scaling Values RS:RI:SS = 5.19072:0:0.00953466 (see PMC3998685)
Convert 2 DICOM as test2/TRA_s603_real (1024x1024x2x1)
compress: "/usr/bin/pigz" -n -f -6 "test2/TRA_s603_real.nii"
slices not stacked: some are phase/real/imaginary maps, others are not. Use 'merge 2D slices' option to force stacking
Dims 704 704 47 1 1
 Distance from first slice:
dx=[0 5.00001 6.00001 7.00001 8.00001 9.00002 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 29 31.0001 32.0001 39.0001 44.0001 45

dcm2niix conversion... [    = ]not mirrored.
compress: "/usr/bin/pigz" -n -f -6 "test2/ANGIO_s904_i00001_real.nii"
Using RWVSlope:RWVIntercept = 5.23419:0
 Philips Scaling Values RS:RI:SS = 5.23419:0:0.00914187 (see PMC3998685)
Convert 1 DICOM as test2/ANGIO_s904_i00010_real (512x512x1x1)
compress: "/usr/bin/pigz" -n -f -6 "test2/ANGIO_s904_i00010_real.nii"
Using RWVSlope:RWVIntercept = 5.23419:0
 Philips Scaling Values RS:RI:SS = 5.23419:0:0.00914187 (see PMC3998685)
Convert 1 DICOM as test2/ANGIO_s904_i00002_real (512x512x1x1)
compress: "/usr/bin/pigz" -n -f -6 "test2/ANGIO_s904_i00002_real.nii"
Using RWVSlope:RWVIntercept = 5.23419:0
 Philips Scaling Values RS:RI:SS = 5.23419:0:0.00914187 (see PMC3998685)
Convert 1 DICOM as test2/ANGIO_s904_i00003_real (512x512x1x1)
compress: "/usr/bin/pigz" -n -f -6 "test2/ANGIO_s904_i00003_real.nii"
Using RWVSlope:RWVIntercept = 5.23419:0
 Philips Scaling Values RS:RI:SS = 5.23419:0:0.00914187 (see PMC3998685)
Convert 1 DICOM as test2/ANGIO_s904_i

0

In [59]:
!ls {dst}

ANGIO_s903_i00001_real.json         Sag_3D_FLAIR_s1201.json
ANGIO_s903_i00001_real.nii.gz       Sag_3D_FLAIR_s1201.nii.gz
ANGIO_s903_i00002_real.json         Sag_3D_FLAIR_s601_Crop_1.nii.gz
ANGIO_s903_i00002_real.nii.gz       Sag_3D_FLAIR_s601.json
ANGIO_s903_i00003_real.json         Sag_3D_FLAIR_s601.nii.gz
ANGIO_s903_i00003_real.nii.gz       Sag_3D_T1_s1101_Crop_1.nii.gz
ANGIO_s903_i00004_real.json         Sag_3D_T1_s1101.json
ANGIO_s903_i00004_real.nii.gz       Sag_3D_T1_s1101.nii.gz
ANGIO_s903_i00005_real.json         Survey_s101_i00001.json
ANGIO_s903_i00005_real.nii.gz       Survey_s101_i00001.nii.gz
ANGIO_s903_i00006_real.json         Survey_s101_i00004.json
ANGIO_s903_i00006_real.nii.gz       Survey_s101_i00004.nii.gz
ANGIO_s903_i00007_real.json         Survey_s101_i00007.json
ANGIO_s903_i00007_real.nii.gz       Survey_s101_i00007.nii.gz
ANGIO_s903_i00008_real.json         T1W_3D_TFE_s201.json
ANGIO_s903_i00008_real.nii.gz       T1W_3D_TFE_s201.nii.gz
ANGIO_s903_i00009_real.jso

In [67]:
!dtip locate test -o 'dst'


[@ locate] begin:
[INFO] Matched series = dict_keys(['xDTImediumisos501a1005'])
[INFO] Copied bvec @ dst/xDTImediumisos501a1005.bval
[INFO] Copied bval @ dst/xDTImediumisos501a1005.bvec
[INFO] Copied nifti @ dst/xDTImediumisos501a1005.nii.gz
[INFO] Copied json @ dst/1_1_DTI_medium_iso_20201228113918_501.json
[@ locate] completed!



In [44]:
output_path = Path(dst)

In [50]:
selected_json = [
    p for p in output_path.glob('*') 
    if (('DTI_medium_iso' in p.stem) and (p.suffix == '.json'))
]
selected_json = [p for p in selected_json if p.stem.split('_')[-1] == series]
selected_json

[PosixPath('test/1_1_DTI_medium_iso_20201228113918_501.json')]

In [51]:
selected_json = [
    p for p in output_path.glob('*') 
    if (('DTI_medium_iso' in p.stem) and (p.suffix == '.json'))
]
selected_json

[PosixPath('test/1_1_DTI_medium_iso_20201228113918_501.json'),
 PosixPath('test/1_1_DTI_medium_iso_20201228113918_401.json')]

In [68]:
import json

In [70]:
json_filepath = '/media/virk/MyEHDD/ITS/2_interm/1_1/1_1_DTI_medium_iso_20201228113918_501.json'
with open(json_filepath) as jfile:
    info = json.load(jfile)

In [72]:
info['EchoTime']

0.08538

In [106]:
from fsl.wrappers import eddy as fsleddy

In [90]:
_b0shape = nib.load(path).shape
# If there are two b0 images i.e. shape=X,Y,Z,2 then perform TOPUP.
if (len(_b0shape) == 4) and (_b0shape.shape[3] == 2):
    topup(path, datain=acqp, out=outpath, verbose=True)

In [2]:
path = '/media/virk/MyEHDD/ITS/2_interm/1_1/b0.nii.gz'
acqp = '/home/virk/devs/WorkProjects/DTIP/acqparams.txt'
outpath = './topup_b0'
foutpath, ioutpath = f'{outpath}_fout', f'{outpath}_iout'
# topup(path, datain=acqp, out=outpath, fout=foutpath, iout=ioutpath, verbose=True)

In [93]:
!ls

topup_b0_fieldcoef.nii.gz  topup_b0_iout.nii.gz  Untitled.ipynb
topup_b0_fout.nii.gz       topup_b0_movpar.txt


In [95]:
from fsl.wrappers.fslmaths import fslmaths

In [109]:
fslmaths(path).Tmean().run('tmean.nii.gz')

{}

In [99]:
!ls

tmean.nii.gz               topup_b0_fout.nii.gz  topup_b0_movpar.txt
topup_b0_fieldcoef.nii.gz  topup_b0_iout.nii.gz  Untitled.ipynb


In [111]:
from fsl.wrappers.bet import bet

In [114]:
bet(path, 'b0_mask', mask=True, robust=True, fracintensity=0.5)

{}

In [3]:
import os
os.chdir('/media/virk/MyEHDD/ITS/2_interm/1_1')

In [4]:
!eddy --imain=xDTImediumisos501a1005.nii.gz \
--mask=b0_avg_mask.nii.gz \
--index=index.txt \
--acqp=acqparams.txt --bvecs=xDTImediumisos501a1005.bvec --bvals=xDTImediumisos501a1005.bval --out=edddddy -v

Reading images
Performing volume-to-volume registration
Running Register
Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 3.113966 
0.626659 
2.475803 

Calculating parameter updates
Iter: 0, Total mss = 2.069119
Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 19.269346 
0.631698 
4.906083 

Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 8.352418 
0.647115 
-6.158126 

Calculating parameter updates
Iter: 1, Total mss = 0.001179
Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 5.199728 
0.655037 
2.266156 

Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 22.222310 
0.638016 
8.252936 

Calculating parameter updates
Iter: 2, Total mss = 0.006818
Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 25.662078 
0.638697 
10.154069 

Loading prediction maker
Evaluating pred

In [122]:
fsleddy.wutils?

In [1]:
from dtip.process import run_eddy
from pathlib import Path

In [2]:
run_eddy(
    input_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/xDTImediumisos501a1005.nii.gz'),
    brain_mask_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/b0_avg_mask.nii.gz'),
    index_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/index.txt'), 
    acqp_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/acqparams.txt'), 
    bvecs_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/xDTImediumisos501a1005.bvec'), 
    bvals_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/xDTImediumisos501a1005.bval'), 
    output_path=Path('/media/virk/MyEHDD/ITS/2_interm/1_1/edddddy'),
)

Running eddy... [=     ]Reading images
Running eddy... [  =   ]Performing volume-to-volume registration
Running Register
Running eddy... [  =   ]Loading prediction maker
Evaluating prediction maker model
Estimated hyperparameters: 3.052662 
0.651102 
2.616334 

Running eddy... [  =   ]Calculating parameter updates
Running eddy... [    = ]Iter: 0, Total mss = 2.140912
Running eddy... [    = ]Loading prediction maker
Evaluating prediction maker model
Running eddy... [   =  ]Estimated hyperparameters: 9.977079 
0.615634 
-2.885202 

Running eddy... [   =  ]Loading prediction maker
Evaluating prediction maker model
Running eddy... [    = ]Estimated hyperparameters: 26.285751 
0.609279 
9.969665 

Calculating parameter updates
Running eddy... [  =   ]Iter: 1, Total mss = 0.004023
Running eddy... [   =  ]Loading prediction maker
Evaluating prediction maker model
Running eddy... [  =   ]Estimated hyperparameters: 12.133953 
0.624033 
-4.473105 

Running eddy... [ =    ]Loading prediction make

Running eddy... [   =  ]

Running eddy... [    = ]Running interleave 1 of MBS
Running eddy... [ =    ]Loading prediction maker
Evaluating prediction maker model
Running eddy... [  =   ]Loading prediction maker
Evaluating prediction maker model
Running eddy... [   =  ]Estimated hyperparameters: 13.865914 
0.615565 
-0.967265 

Running eddy... [ =    ]Loading prediction makerSegmentation violation, Address not mapped, Offending address = 0x50
eddy NEWIMAGE::volume<float>::reinitialize(NEWIMAGE::volume<float> const&, NEWIMAGE::constructionMode) [0x6a02f5]
Running eddy... [  =   ]eddy NEWIMAGE::volume<float>::volume(NEWIMAGE::volume<float> const&, NEWIMAGE::constructionMode) [0x6a0793]
eddy EDDY::ECScanManager::GetSuscHzOffResField(unsigned int, EDDY::ScanType) const [0x5fc2d9]
eddy EDDY::ECScanManager::GetUnwarpedScan(unsigned int, NEWIMAGE::volume<float>&, EDDY::ScanType) const [0x5ff63e]
eddy() [0x536d9e]
eddy EDDY::LoadPredictionMaker(EDDY::EddyCommandLineOptions const&, EDDY::ScanType, EDDY::ECScanManager cons

1

In [31]:
from fsl.wrappers.bet import bet
from pathlib import Path
import nibabel as nib
import subprocess
from dtip.utils import SpinCursor

In [2]:
path = '/media/virk/MyEHDD/ITS/2_interm/1_1/xDTImediumisos501a1005.nii.gz'
mask = '/media/virk/MyEHDD/ITS/2_interm/1_1/b0_avg_mask.nii.gz'

In [30]:
ret_code = subprocess.run([
    'fslsplit', str(path), Path(path).parent/'tmp_dti_bet', '-t'
]).returncode
if ret_code != 0:
    raise RuntimeError("Something wrong with fslsplit command.")

dti_vols_paths = [
    str(p) for p in Path(path).parent.glob('*') 
    if p.stem.startswith('tmp_dti_bet')
]

assert CNF.n_gradients == len(dti_vols_paths)

In [32]:
with SpinCursor():
    for i, dti_path in enumerate(dti_vols_paths, start=1):
        print(f"[{i}/{CNF.n_gradients}] extracting brain...", end=' ')
        bet(dti_path, dti_path, mask=True, robust=True, fracintensity=0.5)
        print('done')

Loading... [=     ][1/16] extracting brain...
Loading... [ =    ]done
[2/16] extracting brain...
Loading... [  =   ]done
[3/16] extracting brain...
Loading... [     =]done
[4/16] extracting brain...
Loading... [ =    ]done
[5/16] extracting brain...
Loading... [=     ]done
[6/16] extracting brain...
Loading... [  =   ]done
[7/16] extracting brain...
Loading... [=     ]done
[8/16] extracting brain...
Loading... [=     ]done
[9/16] extracting brain...
Loading... [ =    ]done
[10/16] extracting brain...
Loading... [ =    ]done
[11/16] extracting brain...
Loading... [ =    ]done
[12/16] extracting brain...
Loading... [=     ]done
[13/16] extracting brain...
Loading... [  =   ]done
[14/16] extracting brain...
Loading... [   =  ]done
[15/16] extracting brain...
Loading... [    = ]done
[16/16] extracting brain...
Loading... [   =  ]done
Done!                                                                       


In [1]:
import nibabel as nib
import numpy as np

In [32]:
func_path = '/media/virk/MyEHDD/templates/IITmean_tensor_256.nii.gz'
path = '/media/virk/MyEHDD/test/JHU_pcl_128.nii.gz'

In [33]:
func = nib.load(func_path)
pclf = nib.load(path)
affine, header = pclf.affine, pclf.header
pcl = pclf.get_fdata()
pcl = np.expand_dims(pcl, -1)
pcl = np.expand_dims(pcl, -1)
za = np.zeros_like(pcl)
dti_pcl = np.concatenate((pcl, pcl, pcl, pcl, pcl, pcl), axis=-1)
pcl.shape, dti_pcl.shape

((128, 128, 128, 1, 1), (128, 128, 128, 1, 6))

In [34]:
print(func.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  5 256 256 256   1   6   0   0]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : symmetric matrix
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 1. 1. 1. 1. 1. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : 0.0
qoffset_y       : 0.0
qoffset_z       : 0.0
srow_x          : [1. 0. 0. 0.]
srow_y   

In [35]:
print(affine)

[[0.84375006 0.         0.         0.60000002]
 [0.         1.03125    0.         0.60000002]
 [0.         0.         0.84375006 0.60000002]
 [0.         0.         0.         1.        ]]


In [36]:
print(func.affine)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
pclf.header.set_intent('symmetric matrix')
pclf.header.set_qform(func.header.get_qform(), code='scanner')
pclf.header.set_sform(func.header.get_sform(), code='scanner')
pclf.update_header()

In [38]:
ni_img = nib.Nifti1Image(dti_pcl, affine=affine, header=func.header)
nib.save(ni_img, '/media/virk/MyEHDD/test/output.nii.gz')

# nib.save(pclf, '/media/virk/MyEHDD/test/output.nii.gz')

In [39]:
func.header.get_intent()

('symmetric matrix', (0.0,), '')

In [40]:
func.header.get_qform()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])